version: "3.8"

services:
  web:
    build: .
    command: python3 app.py
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - app-net
  

  db:
    image: postgres:13
    env_file:
      - .env
    networks:
      - app-net
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  app-net:
    driver: bridge
